name: CVE Scanning for Python

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:  # Run on every push to any branch
  pull_request:  # Run on new pull requests
  workflow_dispatch: # Enable manual run

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@main
      - uses: actions/checkout@v4
      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
