name: Build and Release Wheel

on:
  push:
    tags:
      - '**'  # Trigger on tags like v1.0.0, v2.1.3, etc.

jobs:
  build-and-release:
    name: Build Wheel and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for setuptools_scm to determine version from git tags

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools setuptools_scm wheel pytest-runner

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
